version: "3.7"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - kc_network

  redis:
    image: "redis:latest"
    ports: 
      - "6379:6379"
    networks:
      - kc_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - kc_network
    volumes:
      - ./providers:/opt/keycloak/providers


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: Y
    ports:
       - "1433:1433"
    volumes:
       - sqlserver_data:/var/opt/mssql
    networks:
       - kc_network



  loyalty-service:
    build:
      context: .
      dockerfile: LoyaltyService/Dockerfile
    ports:
      - "8081:8080"
      - "8082:8081"
    depends_on:
      - redis
      - keycloak
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Add any other environment variables your app needs
    networks:
      - kc_network

volumes:
  postgres_data:
    driver: local
  sqlserver_data :
networks:
  kc_network:
    driver: bridge
